---
- name: ensure python and pip is installed
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - python
    - python-pip
  when: redis_cluster_candidate

- name: ensure pexpect is installed
  pip:
    name: pexpect
  when: redis_cluster_candidate

- name: create a redis cluster
  expect:
    command: 'redis-cli --cluster create {{ redis_cluster_nodes | join(" ") }} --cluster-replicas {{ redis_cluster_replicas }}'
    responses:
      ">>> Performing hash slots allocation": 'yes'
  changed_when: false
  when: redis_cluster_candidate
