---
- name: create a redis cluster
  command: 'redis-cli --cluster create {{ redis_cluster_nodes | join(" ") }} --cluster-replicas {{ redis_cluster_replicas }}'
  changed_when: false
  when: redis_cluster_candidate
