---
- name: download redis
  get_url:
    url: '{{ redis_download_url }}'
    dest: '/usr/local/src/redis-{{ redis_version }}.tar.gz'

- name: extract redis tarball
  unarchive:
    src: '/usr/local/src/redis-{{ redis_version }}.tar.gz'
    dest: '/usr/local/src'
    creates: '/usr/local/src/redis-{{ redis_version }}/Makefile'
    copy: false
