---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance-1
    groups:
      - redis
      - candidate
    image: lackofimagination/ubuntu-systemd:latest
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 50000
    privileged: true
    memory: 512M
    pre_build_image: true
  - name: instance-2
    groups:
      - redis
    image: lackofimagination/ubuntu-systemd:latest
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 50000
    privileged: true
    memory: 512M
    pre_build_image: true
  - name: instance-3
    groups:
      - redis
    image: lackofimagination/ubuntu-systemd:latest
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 50000
    privileged: true
    memory: 512M
    pre_build_image: true
  - name: instance-4
    groups:
      - redis
    image: lackofimagination/ubuntu-systemd:latest
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 50000
    privileged: true
    memory: 512M
    pre_build_image: true
  - name: instance-5
    groups:
      - redis
    image: lackofimagination/ubuntu-systemd:latest
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 50000
    privileged: true
    memory: 512M
    pre_build_image: true
  - name: instance-6
    groups:
      - redis
    image: lackofimagination/ubuntu-systemd:latest
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 50000
    privileged: true
    memory: 512M
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: cluster
verifier:
  name: testinfra
  lint:
    name: flake8
