---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: master-1
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 25000
    privileged: true
    memory: 128M
    pre_build_image: true
  - name: master-2
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 25000
    privileged: true
    memory: 128M
    pre_build_image: true
  - name: master-3
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 25000
    privileged: true
    memory: 128M
    pre_build_image: true
  - name: slave-1
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 25000
    privileged: true
    memory: 128M
    pre_build_image: true
  - name: slave-2
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 25000
    privileged: true
    memory: 128M
    pre_build_image: true
  - name: slave-3
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 25000
    privileged: true
    memory: 128M
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: cluster
verifier:
  name: testinfra
  lint:
    name: flake8
